#!/bin/bash

dir="/scratchNVM5/jmun/workloads"
log="./out/micro1/"
mkdir -p ${log}
wl=(
K8_E1024_2M_exp_PQ_1.0
K16_E1024_2M_exp_PQ_1.0
K32_E1024_2M_exp_PQ_1.0
K64_E1024_2M_exp_PQ_1.0
K128_E1024_2M_exp_PQ_1.0
K256_E1024_2M_exp_PQ_1.0
K512_E1024_2M_exp_PQ_1.0
)

tries=3
for w in "${wl[@]}"
do
  echo $w
  mkdir -p "${log}/${w}/"
  for hash in $(seq 6 1 7)
  do
    python exp.py ${tries} ./micro1 ./ ${hash} ${dir}/${w}/in.txt ${dir}/${w}/out.txt > ${log}/${w}/${hash}-result.txt
  done
done
